import { format, subDays } from "date-fns";

// Generate unique IDs
const generateId = (prefix) =>
  `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// Generate order ID
export const generateOrderId = () => {
  const randomNum = Math.floor(1000 + Math.random() * 9000);
  return `ORD-${randomNum}`;
};

// Sample Users
export const sampleUsers = [
  {
    id: "user_1",
    name: "Michael Johnson",
    email: "michael@kasugeeta.com",
    password: "password123",
    role: "manager",
    phone: "+1 (555) 123-4567",
    address: "123 Main Street, San Francisco, CA 94107",
    avatar: "MJ",
    isActive: true,
    createdAt: "2023-01-15T10:30:00Z",
  },
  {
    id: "user_2",
    name: "Sarah Wilson",
    email: "sarah@kasugeeta.com",
    password: "password123",
    role: "manager",
    phone: "+1 (555) 987-6543",
    avatar: "SW",
    isActive: true,
    createdAt: "2023-02-20T14:45:00Z",
  },
];

// Sample Categories
export const sampleCategories = [
  {
    id: "cat_1",
    name: "Popcorn",
    description: "Freshly popped popcorn in various flavors",
    image: "",
    isActive: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "cat_2",
    name: "Soft Drinks",
    description: "Cold beverages and refreshments",
    image: "",
    isActive: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "cat_3",
    name: "Desserts",
    description: "Sweet treats and desserts",
    image: "",
    isActive: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "cat_4",
    name: "Snacks",
    description: "Quick snacks and bites",
    image: "",
    isActive: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "cat_5",
    name: "Combo Meals",
    description: "Special combo offers",
    image: "",
    isActive: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
];

// Sample Items
export const sampleItems = [
  {
    id: "item_1",
    name: "Classic Popcorn (Large)",
    categoryId: "cat_1",
    description: "Classic butter popcorn, large size",
    price: 8.99,
    cost: 2.5,
    stock: 42,
    image: "",
    isAvailable: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "item_2",
    name: "Caramel Popcorn (Medium)",
    categoryId: "cat_1",
    description: "Sweet caramel popcorn, medium size",
    price: 6.99,
    cost: 2.0,
    stock: 28,
    image: "",
    isAvailable: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "item_3",
    name: "Coca-Cola (500ml)",
    categoryId: "cat_2",
    description: "Cold Coca-Cola, 500ml bottle",
    price: 3.5,
    cost: 1.0,
    stock: 120,
    image: "",
    isAvailable: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "item_4",
    name: "Pepsi (500ml)",
    categoryId: "cat_2",
    description: "Cold Pepsi, 500ml bottle",
    price: 3.5,
    cost: 1.0,
    stock: 95,
    image: "",
    isAvailable: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "item_5",
    name: "Chocolate Brownie",
    categoryId: "cat_3",
    description: "Rich chocolate brownie with nuts",
    price: 5.99,
    cost: 1.5,
    stock: 24,
    image: "",
    isAvailable: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
  {
    id: "item_6",
    name: "Ice Cream Sundae",
    categoryId: "cat_3",
    description: "Vanilla ice cream with chocolate sauce",
    price: 6.5,
    cost: 2.0,
    stock: 18,
    image: "",
    isAvailable: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-10-22T09:15:00Z",
  },
];

// Sample Orders
export const sampleOrders = [
  {
    orderId: "ORD-7845",
    customer: {
      name: "Alex Turner",
      email: "alex@email.com",
      phone: "+1 (555) 111-2233",
      address: "123 Broadway, New York, NY 10001",
    },
    items: [
      {
        itemId: "item_1",
        name: "Classic Popcorn (Large)",
        price: 8.99,
        quantity: 2,
        subtotal: 17.98,
      },
      {
        itemId: "item_3",
        name: "Coca-Cola (500ml)",
        price: 3.5,
        quantity: 1,
        subtotal: 3.5,
      },
      {
        itemId: "item_5",
        name: "Chocolate Brownie",
        price: 5.99,
        quantity: 1,
        subtotal: 5.99,
      },
    ],
    subtotal: 27.47,
    taxRate: 5.0,
    taxAmount: 1.37,
    total: 28.84,
    status: "pending",
    paymentMethod: "card",
    paymentStatus: "paid",
    orderType: "dine-in",
    tableNumber: "12",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    orderId: "ORD-7844",
    customer: {
      name: "Maria Garcia",
      email: "maria@email.com",
      phone: "+1 (555) 222-3344",
    },
    items: [
      {
        itemId: "item_2",
        name: "Caramel Popcorn (Medium)",
        price: 6.99,
        quantity: 1,
        subtotal: 6.99,
      },
      {
        itemId: "item_4",
        name: "Pepsi (500ml)",
        price: 3.5,
        quantity: 2,
        subtotal: 7.0,
      },
    ],
    subtotal: 13.99,
    taxRate: 5.0,
    taxAmount: 0.7,
    total: 14.69,
    status: "pending",
    paymentMethod: "cash",
    paymentStatus: "pending",
    orderType: "takeaway",
    notes: "Extra napkins please",
    createdAt: format(subDays(new Date(), 1), "yyyy-MM-dd'T'14:30:00'Z'"),
    updatedAt: format(subDays(new Date(), 1), "yyyy-MM-dd'T'14:30:00'Z'"),
  },
  {
    orderId: "ORD-7843",
    customer: {
      name: "David Kim",
      email: "david@email.com",
      phone: "+1 (555) 333-4455",
      address: "456 Park Ave, San Francisco, CA 94107",
    },
    items: [
      {
        itemId: "item_1",
        name: "Classic Popcorn (Large)",
        price: 8.99,
        quantity: 1,
        subtotal: 8.99,
      },
      {
        itemId: "item_3",
        name: "Coca-Cola (500ml)",
        price: 3.5,
        quantity: 3,
        subtotal: 10.5,
      },
    ],
    subtotal: 19.49,
    taxRate: 5.0,
    taxAmount: 0.97,
    total: 20.46,
    status: "accepted",
    paymentMethod: "mobile",
    paymentStatus: "paid",
    orderType: "delivery",
    deliveryAddress: "456 Park Ave, San Francisco, CA 94107",
    notes: "Ring doorbell twice",
    createdAt: format(subDays(new Date(), 1), "yyyy-MM-dd'T'12:15:00'Z'"),
    updatedAt: format(subDays(new Date(), 1), "yyyy-MM-dd'T'12:20:00'Z'"),
  },
  {
    orderId: "ORD-7842",
    customer: {
      name: "Lisa Wang",
      email: "lisa@email.com",
      phone: "+1 (555) 444-5566",
    },
    items: [
      {
        itemId: "item_6",
        name: "Ice Cream Sundae",
        price: 6.5,
        quantity: 2,
        subtotal: 13.0,
      },
    ],
    subtotal: 13.0,
    taxRate: 5.0,
    taxAmount: 0.65,
    total: 13.65,
    status: "completed",
    paymentMethod: "card",
    paymentStatus: "paid",
    orderType: "dine-in",
    tableNumber: "8",
    notes: "",
    createdAt: format(subDays(new Date(), 2), "yyyy-MM-dd'T'18:45:00'Z'"),
    updatedAt: format(subDays(new Date(), 2), "yyyy-MM-dd'T'19:15:00'Z'"),
  },
  {
    orderId: "ORD-7841",
    customer: {
      name: "James Miller",
      email: "james@email.com",
      phone: "+1 (555) 555-6677",
    },
    items: [
      {
        itemId: "item_2",
        name: "Caramel Popcorn (Medium)",
        price: 6.99,
        quantity: 2,
        subtotal: 13.98,
      },
      {
        itemId: "item_5",
        name: "Chocolate Brownie",
        price: 5.99,
        quantity: 1,
        subtotal: 5.99,
      },
    ],
    subtotal: 19.97,
    taxRate: 5.0,
    taxAmount: 1.0,
    total: 20.97,
    status: "completed",
    paymentMethod: "online",
    paymentStatus: "paid",
    orderType: "takeaway",
    notes: "",
    createdAt: format(subDays(new Date(), 3), "yyyy-MM-dd'T'16:30:00'Z'"),
    updatedAt: format(subDays(new Date(), 3), "yyyy-MM-dd'T'16:45:00'Z'"),
  },
];

// Sample Business Settings
export const sampleBusinessSettings = {
  businessName: "KASU GEETA ARTS Restaurant",
  address: "123 Main Street, San Francisco, CA 94107",
  phone: "+1 (555) 123-4567",
  email: "info@kasugeeta.com",
  currency: "USD",
  timeZone: "America/Los_Angeles",
  dateFormat: "DD/MM/YYYY",
  businessHours: {
    monday: { open: "9:00", close: "22:00" },
    tuesday: { open: "9:00", close: "22:00" },
    wednesday: { open: "9:00", close: "22:00" },
    thursday: { open: "9:00", close: "22:00" },
    friday: { open: "9:00", close: "23:00" },
    saturday: { open: "10:00", close: "23:00" },
    sunday: { open: "10:00", close: "21:00" },
  },
  lowStockAlert: 10,
  autoRefreshOrders: true,
  autoRefreshInterval: 30,
  orderNotificationSound: true,
  updatedAt: "2023-10-22T09:15:00Z",
};

// Sample Tax Configuration
export const sampleTaxConfig = {
  taxPercentage: 5.0,
  taxInclusive: false,
  updatedAt: "2023-10-22T09:15:00Z",
};
